itemcatalog/views/catalog.py
""" Module summary:
Functions:
  catalogShow - Show the catalog for a given farm."
  catalogManage - Show the catalog for a given farm in manage mode.
  newItem - Create a new catalog item and add it to the database.
  editCatalogItem - Make changes to an existing catalog item.
  deleteCatalogItem - Delete an existing catalog item.  
"""

from flask import Blueprint, render_template, request, redirect
from flask import url_for, flash
from flask import session as login_session

from itemcatalog.database.dbsetup import Farm, CatalogItem, itemCategories
from itemcatalog.database.dbconnect import db_session
from itemcatalog.views.util import imageUploadItem, imageDeleteItem

from util import login_required

############################################################################

catalog = Blueprint("catalog", __name__)

@catalog.route("/farms/<int:farm_id>")
@catalog.route("/farms/<int:farm_id>/catalog")
def catalogShow(farm_id):
  """Show the catalog for a given farm."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  username = login_session.get("username")
  items_list = db_session.query(CatalogItem).filter_by(farm_id=farm_id).all()

  items = {}
  for item in items_list:
    if items.has_key(item.category):
      items[item.category].append(item)
    else:
      items[item.category] = [item]

  return render_template("catalog.html",
                         farm=farm,
                         items=items,
                         itemCategories=itemCategories,
                         username=username)

                         
@catalog.route("/farms/<int:farm_id>/catalog/manage")
@login_required
def catalogManage(farm_id):
  """Show the catalog for a given farm in manage mode."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  items_list = db_session.query(CatalogItem).filter_by(farm_id = farm_id).all()
  items = {}
  for item in items_list:
    if items.has_key(item.category):
      items[item.category].append(item)
    else:
      items[item.category] = [item]

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    return render_template("catalogManage.html",
                           farm=farm,
                           items=items,
                           itemCategories=itemCategories,
                           username=username)

  else:
    return redirect(url_for("error.errorShow"))


@catalog.route("/farms/<int:farm_id>/catalog/new", methods=["GET","POST"])
@login_required
def newItem(farm_id):
  """Create a new catalog item and add it to the database."""
  farm = db_session.query(Farm).filter_by(id = farm_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    if request.method == "POST":
      name = request.form.get("name")
      description = request.form.get("description")
      price = request.form.get("price")
      category = request.form.get("category")

      name_error = None
      category_error = None

      if not name:
        name_error = True
      if not category:
        category_error = True

      if name_error or category_error:
        return render_template("catalogItemNew.html",
                               name_error=name_error,
                               category_error=category_error,
                               farm=farm,
                               itemCategories=itemCategories,
                               username=username)

      newItem = CatalogItem(name=name,
                            description=description,
                            price=price,
                            category=category,
                            farm_id=farm_id,
                            user_id=farm.user_id,
                            picture=None)
      db_session.add(newItem)
      db_session.commit()

      picture = request.files["picture"]
      if picture:
        db_session.refresh(newItem)
        picture_name = imageUploadItem(farm_id=farm_id,
                                       item_id=newItem.id,
                                       file=picture)
        newItem.picture = picture_name
        db_session.add(newItem)
        db_session.commit()

      flash("New Item Successfully Created: %s" % (newItem.name))
      return redirect(url_for("catalog.catalogManage", farm_id=farm_id))

    else:
      return render_template("catalogItemNew.html",
                             farm=farm,
                             itemCategories=itemCategories,
                             username=username)

  else:
    return redirect(url_for("error.errorShow"))


@catalog.route("/farms/<int:farm_id>/catalog/<int:item_id>/edit",
                    methods=["GET","POST"])
@login_required
def editCatalogItem(farm_id, item_id):
  """Make changes to an existing catalog item."""
  farm = db_session.query(Farm).filter_by(id = farm_id).one()
  item = db_session.query(CatalogItem).filter_by(id = item_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == item.user_id:
    if request.method == "POST":
      name = request.form.get("name")
      description = request.form.get("description")
      price = request.form.get("price")
      category = request.form.get("category")

      name_error = None
      category_error = None

      if not name:
        name_error = True
      if not category:
        category_error = True

      if name_error or category_error:
        return render_template("catalogItemEdit.html",
                               name_error=name_error,
                               category_error=category_error,
                               farm=farm,
                               item=item,
                               itemCategories=itemCategories,
                               username=username)

      item.name = request.form["name"]
      item.description = request.form["description"]
      item.price = request.form["price"]
      item.category = request.form["category"]

      f = request.form
      existing_pic = item.picture
      remove_pic = "removepicture" in f.keys() and \
                      f["removepicture"] == "no-pic"
      new_pic = request.files["picture"]

      if existing_pic:
        if remove_pic:
          imageDeleteItem(filename=item.picture)
          item.picture = None

        elif new_pic:
          imageDeleteItem(filename=item.picture)
          item.picture = imageUploadItem(farm_id=farm.id,
                                         item_id=item.id,
                                         file=new_pic)

      elif new_pic:
          item.picture = imageUploadItem(farm_id=farm.id,
                                         item_id=item.id,
                                         file=new_pic)

      db_session.add(item)
      db_session.commit()
      flash("Item Successfully Edited: %s" % (item.name))
      return redirect(url_for("catalog.catalogManage", farm_id=farm_id))

    else:
      return render_template("catalogItemEdit.html",
                             farm=farm,
                             item=item,
                             itemCategories=itemCategories,
                             username=username)

  return redirect(url_for("error.errorShow"))

  
@catalog.route("/farms/<int:farm_id>/catalog/<int:item_id>/delete",
                      methods=["GET","POST"])
@login_required                      
def deleteCatalogItem(farm_id, item_id):
  """Delete an existing catalog item."""
  farm = db_session.query(Farm).filter_by(id = farm_id).one()
  item = db_session.query(CatalogItem).filter_by(id = item_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == item.user_id:
    if request.method == "POST":
      db_session.delete(item)
      db_session.commit()

      if item.picture:
        imageDeleteItem(filename=item.picture)

      flash("Item Successfully Deleted: %s" % (item.name))
      return redirect(url_for("catalog.catalogManage", farm_id=farm_id))

    else:
      return render_template("catalogItemDelete.html",
                             farm=farm,
                             item=item,
                             username=username)

  return redirect(url_for("error.errorShow"))
  

itemcatalog/views/event.py
""" Module summary:
Functions:
  eventShow - Show the events for a given farm.
  eventManage - Show the events for a given farm in manage mode.
  eventNew - Create a new event.
  eventEdit - Edit an event.
  eventDelete - Delete an event.  
"""

from flask import Blueprint, render_template, request, redirect, url_for
from flask import flash
from flask import session as login_session

from itemcatalog.database.dbsetup import Farm, Event
from itemcatalog.database.dbconnect import db_session

from util import login_required

############################################################################

event = Blueprint("event", __name__)

@event.route("/farms/<int:farm_id>/events")
def eventShow(farm_id):
  """Show the events for a given farm."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  events = db_session.query(Event).filter_by(farm_id=farm_id).all()
  username = login_session.get("username")

  return render_template("events.html",
                         farm=farm,
                         events=events,
                         username=username)

                         
@event.route("/farms/<int:farm_id>/events/manage")
@login_required
def eventManage(farm_id):
  """Show the events for a given farm in manage mode."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  events = db_session.query(Event).filter_by(farm_id=farm_id).all()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    return render_template("eventsManage.html",
                           farm=farm,
                           events=events,
                           username=username)

  else:
    return redirect(url_for("error.errorShow"))


@event.route("/farms/<int:farm_id>/events/new", methods=["GET","POST"])
@login_required
def eventNew(farm_id):
  """Create a new event."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    if request.method == "POST":
      if not request.form["name"]:
        return render_template("eventNew.html",
                               farm=farm,
                               name_error=True,
                               username=username)

      event = Event(name = request.form["name"],
                     description = request.form["description"],
                     farm_id=farm.id,
                     user_id=user_id)

      db_session.add(event)
      flash("New Event Successfully Created: %s" % event.name)
      db_session.commit()
      return redirect(url_for("event_manage.eventManage",farm_id=farm.id))

    else:
      return render_template("eventNew.html",
                             farm=farm,
                             username=username)

  else:
    return redirect(url_for("error.errorShow"))

    
@event.route("/farms/<int:farm_id>/events/<int:event_id>/edit",
            methods=["GET","POST"])
@login_required
def eventEdit(farm_id, event_id):
  """Edit an event."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  event = db_session.query(Event).filter_by(id=event_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    if request.method == "POST":
      if not request.form["name"]:
        return render_template("eventEdit.html",
                               farm=farm,
                               event=event,
                               name_error=True,
                               username=username)

      event.name = request.form["name"]
      event.description = request.form["description"]

      db_session.add(event)
      db_session.commit()
      flash("Event Successfully Edited: %s" % event.name)
      return redirect(url_for("event_manage.eventManage",farm_id=farm.id))

    else:
      return render_template("eventEdit.html",
                             farm=farm,
                             event=event,
                             username=username)

  else:
    return redirect(url_for("error.errorShow"))


@event.route("/farms/<int:farm_id>/events/<int:event_id>/delete",
            methods=["GET","POST"])
@login_required
def eventDelete(farm_id, event_id):
  """Delete an event."""
  farm = db_session.query(Farm).filter_by(id=farm_id).one()
  event = db_session.query(Event).filter_by(id=event_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  if user_id == farm.user_id:
    if request.method == "POST":
      db_session.delete(event)
      db_session.commit()

      flash("Event Successfully Deleted: %s" % (event.name))
      return redirect(url_for("event_manage.eventManage",farm_id=farm.id))

    else:
      return render_template("eventDelete.html",
                             farm=farm,
                             event=event,
                             username=username)

  else:
    return redirect(url_for("error.errorShow"))

itemcatalog/views/farm.py
""" Module summary:
Functions:
  farmsShowAll - Show all farms.
  farmsManage - Show all farms belonging to the current user.
  farmNew - Create a new farm and add it to the database.
  farmDelete - Delete an existing farm.  
"""

from flask import Blueprint, render_template, request, redirect, url_for
from flask import flash
from flask import session as login_session

from sqlalchemy import asc

from itemcatalog.database.dbsetup import Farm
from itemcatalog.database.dbconnect import db_session
from itemcatalog.views.util import imageDeleteProfile

from util import login_required

############################################################################

farm = Blueprint("farm", __name__)

@farm.route("/farms")
def farmsShowAll():
  """Show all farms."""
  farms = db_session.query(Farm).order_by(asc(Farm.name))

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  return render_template("farms.html",
                         farms=farms,
                         username=username)


@farm.route("/farms/manage", methods=["GET","POST"])
@login_required
def farmsManage():
  """Show all farms belonging to the current user."""
  user_id = login_session.get("user_id")
  username = login_session.get("username")
  
  # If someone is logged in, show them their farms:
  user_farms = db_session.query(Farm).filter_by(
                user_id=user_id).order_by(asc(Farm.name))
  user_farms = [farm for farm in user_farms]
  return render_template("farmsManage.html",
                         user_farms=user_farms,
                         username=username)
                         

@farm.route("/farms/new", methods=["GET","POST"])
@login_required
def farmNew():
  """Create a new farm and add it to the database."""
  user_id = login_session.get("user_id")
  username = login_session.get("username")
 
  # Check that the user_id argument matches the login_session user_id.
  if request.method == "POST":
    if not request.form["name"]:
      return render_template("farmNew.html",
                             name_error=True,
                             username=username)

    newFarm = Farm(name = request.form["name"],
                   location = request.form["location"],
                   description = request.form["description"],
                   picture = None,
                   user_id=login_session["user_id"])
    db_session.add(newFarm)
    db_session.commit()

    picture = request.files["picture"]
    if picture:
      db_session.refresh(newFarm)
      picture_name = imageUploadProfile(farm_id=newFarm.id, file=picture)
      newFarm.picture = picture_name
      db_session.add(newFarm)
      db_session.commit()

    flash("New Farm %s Successfully Created" % newFarm.name)
    return redirect(url_for("farm.farmsManage"))

  else:
    return render_template("farmNew.html",
                           username=username)

  return render_template("farmNew.html",
                         error=request.files["picture"])


@farm.route("/farms/<int:farm_id>/delete", methods=["GET","POST"])
@login_required
def farmDelete(farm_id):
  """Delete an existing farm."""
  farm = db_session.query(Farm).filter_by(id = farm_id).one()

  user_id = login_session.get("user_id")
  username = login_session.get("username")

  # Check that the login_session user_id matches the farm user_id:
  if user_id == farm.user_id:
    if request.method == "POST":
      if farm.picture:
        imageDeleteProfile(filename=farm.picture)

      db_session.delete(farm)
      db_session.commit()
      flash("Farm Successfully Deleted: %s" % (farm.name))
      return redirect(url_for("farm.farmsManage"))

    else:
      return render_template("farmDelete.html",
                              farm=farm,
                              username=username)

  else:
    return redirect(url_for("catalog.catalogShow",farm_id=farm_id))

itemcatalog/views/index.py
""" Module summary:
Functions:
  showIndex - Show site home.
"""

from flask import Blueprint, render_template
from flask import session as login_session

from sqlalchemy import asc

############################################################################

index = Blueprint("index", __name__)

@index.route("/")
def showIndex():
  """Show site home."""
  user_id = login_session.get("user_id")
  username = login_session.get("username")

  return render_template("index.html",
                         username=username)

itemcatalog/templates/catalog.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row small-banner">
      <div class="col-xs-12 padding-none">
        <h1>{{ farm.name }}</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="farm-tabs">
      <li class="active"><a href="{{ url_for('catalog.catalogShow',farm_id=farm.id) }}">Catalog</a></li>
      <li><a href="{{ url_for('profile.profileShow',farm_id=farm.id) }}">Profile</a></li>
      <li><a href="{{ url_for('event.eventShow',farm_id=farm.id) }}">Events</a></li>
    </ul>

    <div class="main-panel">
      <div class="sub-panel">

        <div class="row flash">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              <ul>
                {% for message in messages %}
                  <li> <strong> {{ message }} </strong> </li>
                {% endfor %}
              </ul>
            {% endif %}
          {% endwith %}
        </div>

        {% if items %}
          {% for category in itemCategories %}
            {% if category in items.keys() %}
              <div class="row">
                <h2 class="catalog">{{ category }}</h2>
              </div>
              {% for i in items[category] %}
                <div class="row">
                  <div class="col-xs-12 item">
                    <h3 class="profile">{{ i.name }}</h3>
                    {% if i.picture %}
                      <img src="{{ url_for('static',filename="".join(['userImages/item/',i.picture])) }}" class="img-float" alt="Profile picture" title=""/>
                    {% endif %}
                    <p>{{ i.description }}</p>
                    <p class="item-price">{{ i.price }}</p>

                    <div>
                      <a href="#" class="buy-link">Buy/Barter</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% endif %}
          {% endfor %}

        {% else %}
          <div class="row">
            <h3>No items yet ...</h3>
          </div>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

itemcatalog/templates/catalogItemDelete.html
{% extends "base.html" %}

{% block content %}
  <div class="row small-banner">
    <div class="col-xs-12 padding-none">
      <h1>{{ farm.name }}</h1>
      <p>Manage Mode</p>
    </div>
  </div>

  <div class="container">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="farm-tabs">
      <li class="active"><a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}">Catalog</a></li>
      <li><a href="{{ url_for('profile.profileManage',farm_id=farm.id) }}">Profile</a></li>
      <li><a href="{{ url_for('event.eventManage',farm_id=farm.id) }}">Events</a></li>
    </ul>

    <div class="main-panel">
      <div class="sub-panel">

        <div class="row">
          <h2 class="catalog">Are you sure you want to delete this item?</h2>
        </div>

        <form action="#" method="post">
          <div class="row">
            <div class="col-xs-12 item">
              <h3 class="profile">{{ item.name }}</h3>
              {% if item.picture %}
                <img src="{{ url_for('static',filename="".join(['userImages/item/',item.picture])) }}" class="img-float" alt="Profile picture" title=""/>
              {% endif %}
              <p>{{ item.description }}</p>
              <p class="item-price">{{ item.price }}</p>
            </div>
          </div>

          <div class="row">
            <div class="padding-top">
              <div id="center-btn-container">
                <button type="submit" class="btn btn-default" id="save-btn">
                  Delete
                </button>

                <a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}" id="cancel-btn">
                  Cancel
                </a>
              </div>
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

itemcatalog/templates/catalogItemEdit.html
{% extends "base.html" %}

{% block content %}
  <div class="row small-banner">
    <div class="col-xs-12 padding-none">
      <h1>{{ farm.name }}</h1>
      <p>Manage Mode</p>
    </div>
  </div>

  <div class="container">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="farm-tabs">
      <li class="active"><a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}">Catalog</a></li>
      <li><a href="{{ url_for('profile.profileManage',farm_id=farm.id) }}">Profile</a></li>
      <li><a href="{{ url_for('event.eventManage',farm_id=farm.id) }}">Events</a></li>
    </ul>

    <div class="main-panel">
      <div class="sub-panel">

        <div class="row">
          <h2>Edit this item:</h2>
        </div>

        <form action="#" method="post" enctype="multipart/form-data">
          <div class="row">
            <div class="col-xs-9 padding-top">
              <label for="name">Name:</label>
              <input class="form-control" type="text" maxlength="250" name="name" value="{{ item.name }}">
              {% if name_error %}
                <p class="red">You must enter an item name.</p>
              {% endif %}
            </div>
          </div>

          <div class="row">
            <div class="col-xs-9 padding-top">
              <label for="description">Description:</label>
              <textarea class="form-control" cols="100" rows="3" name="description">{{ item.description }}</textarea>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-9 padding-top">
              <label for="price">Price:</label>
              <div>
                <p class="inline"></p><input class="form-control" id="price-input" type="text" maxlength="250" name="price" value="{{ item.price }}">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-9 padding-top">
              <label for="category">Category:</label>
              <select class="form-control" name="category">
                {% for category in itemCategories %}
                  {% if item.category == category %}
                    <option selected value="{{ category }}">{{ category }}</option>
                  {% else %}
                    <option value="{{ category }}">{{ category }}</option>
                  {% endif %}
                {% endfor %}
              </select>
              {% if category_error %}
                <p class="red">You must select a category.</p>
              {% endif %}
            </div>
          </div>

          {% if item.picture %}
            <div class="row">
              <div class="col-xs-9 padding-top">
                <div class="form-group">
                  <label>Picture:</label>
                  <div>
                    <img src="{{ url_for('static', filename="".join(['userImages/item/',item.picture])) }}" class="img-block" alt="Profile picture" title=""/>
                  </div>
                </div>
              </div>

              <div class="col-xs-9">
                <div class="form-group">
                  <label for="picture">Select a New Picture:</label>
                  <input type="file" class="form-control" name="picture"/>

                  <label for="removepicture">Or Select Here for No Picture:</label>
                  <input type="checkbox" name="removepicture" value="no-pic"/>
                </div>
              </div>
            </div>
          {% else %}
            <div class="row">
              <div class="col-xs-9 padding-top">
                <div class="form-group">
                  <label for="picture">Select a Profile Picture:</label>
                  <input type="file" class="form-control" name="picture"/>
                </div>
              </div>
            </div>
          {% endif %}

          <div class="row">
            <div class="padding-top">
              <div id="center-btn-container">
                <button type="submit" class="btn btn-default" id="save-btn">
                  Update
                </button>

                <a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}" id="cancel-btn">
                  Cancel
                </a>
              </div>
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

itemcatalog/templates/eventDelete.html
{% extends "base.html" %}

{% block content %}
  <div class="row small-banner">
    <div class="col-xs-12 padding-none">
      <h1>{{ farm.name }}</h1>
      <p>Manage Mode</p>
    </div>
  </div>

  <div class="container">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="farm-tabs">
      <li><a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}">Catalog</a></li>
      <li><a href="{{ url_for('profile.profileManage',farm_id=farm.id) }}">Profile</a></li>
      <li class="active"><a href="{{ url_for('event.eventManage',farm_id=farm.id) }}">Events</a></li>
    </ul>

    <div class="main-panel">
      <div class="sub-panel">

        <div class="row">
          <h2 class="catalog">Are you sure you want to delete this event?</h2>
        </div>

        <form action="#" method="post">
          <div class="row">
            <div class="item">
              <h4>Name:</h4>
              <p>{{ event.name }}</p>

              <h4>Description:</h4>
              <p>{{ event.description }}</p>
            </div>
          </div>

          <div class="row">
            <div class="padding-top">
              <div id="center-btn-container">
                <button type="submit" class="btn btn-default" id="save-btn">
                  Delete
                </button>

                <a href="{{ url_for('event.eventManage',farm_id=farm.id) }}" id="cancel-btn">
                  Cancel
                </a>
              </div>
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

itemcatalog/templates/eventsManage.html
{% extends "base.html" %}

{% block content %}
  <div class="row small-banner">
    <div class="col-xs-12 padding-none">
      <h1>{{ farm.name }}</h1>
      <p>Manage Mode</p>
    </div>
  </div>

  <div class="container">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="farm-tabs">
      <li><a href="{{ url_for('catalog.catalogManage',farm_id=farm.id) }}">Catalog</a></li>
      <li><a href="{{ url_for('profile.profileManage',farm_id=farm.id) }}">Profile</a></li>
      <li class="active"><a href="{{ url_for('event.eventManage',farm_id=farm.id) }}">Events</a></li>
    </ul>

    <div class="main-panel">
      <div class="sub-panel">

        <div class="row flash">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              <ul>
                {% for message in messages %}
                  <li> <strong> {{ message }} </strong> </li>
                {% endfor %}
              </ul>
            {% endif %}
          {% endwith %}
        </div>

        {% if events %}
          <div class="row">
            <h2 class="event">Events</h2>
          </div>
          {% for e in events %}
            <div class="row">
              <div class="item">
                <h3>{{ e.name }}</h3>
                <p>{{ e.description }}</p>

                <a href="{{ url_for('event.eventEdit',farm_id=farm.id,event_id=e.id) }}" class="inline">Edit</a>
                <p class="inline">|</p>
                <a href="{{ url_for('event.eventDelete',farm_id=farm.id,event_id=e.id) }}" class="inline">Delete</a>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="row">
            <h3>No upcoming events. Please check back later.</h3>
          </div>
        {% endif %}

        <div class="v-50">
        </div>
        <div class="row">
          <div id="center-btn-container">
            <a href="{{ url_for('event.eventNew',farm_id=farm.id) }}" id="solid-a-btn">
              Add Event
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

itemcatalog/templates/footer.html
<div class="container" id="footer-container">
  <!-- Bootstrap Navigation Bar -->
  <nav class="navbar navbar-default navbar-static-bottom" id="footer">
    <div class="container-fluid">

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="row col-xs-offset-1">
          <a href="{{ url_for('index.showIndex') }}" role="button" class="navbar-brand footer-item" id="footer-brand">Farm Finder</a>
          <a href="/" role="button" class="navbar-brand footer-item">About</a>
          <a href="/" role="button" class="navbar-brand footer-item">Contact Us</a>
      </div>

    </div>
  </nav>
</div>

itemcatalog/templates/menu.html
<div class="container" id="menu-div">
  <!-- Bootstrap Navigation Bar -->
  <nav class="navbar navbar-default navbar-static" id="menu">

    <ul class="nav nav-tabs nav-justified" id="menu-tabs">
      {% if username %}
        <li></li>
        <li></li>
        <li><a href="{{ url_for('farm.farmsShowAll') }}" id="view-btn">All Farms</a></li>
        <li></li>
        <li><a href="{{ url_for('farm.farmsManage') }}" id="manage-btn">My Farms</a></li>
        <li></li>
        <li><a href="#" id="profile-btn">My Profile</a></li>
        <li></li>
        <li><a href="#" id="discussion-btn">Discussions</a></li>
        <li></li>
        <li></li>
      {% else %}
        <li></li>
        <li></li>
        <li><a href="{{ url_for('farm.farmsShowAll') }}" id="view-btn">All Farms</a></li>
        <li></li>
        <li><a href="#" id="discussion-btn">Discussions</a></li>
        <li></li>
        <li></li>
      {% endif %}
    </ul>

  </nav>
</div>